export const teamData = {
 'White Wolves': {
        score:0,
        wickets:0, balls:0.0,
        runRate:0,
        extras:0,
        players:{
            'Sahan':{bat:0,ball:0},
            'Kithmina':{bat:0,ball:0},
            'Daham':{bat:0,ball:0},
            'Mohommad':{bat:0,ball:0},
            'Hirun' :{bat:0,ball:0},
            'Sakith' :{bat:0,ball:0},
            'Randinu' :{bat:0,ball:0},
            'Ushan' :{bat:0,ball:0},
            'Anjana' :{bat:0,ball:0},
            'Helini' :{bat:0,ball:0},
            'Savithi' :{bat:0,ball:0},
            'Chathurangi' :{bat:0,ball:0},
            'Heliya' :{bat:0,ball:0},
            'Kevin' :{bat:0,ball:0},
            'Manthila' :{bat:0,ball:0},
            'Isurika' :{bat:0,ball:0},
            'Nithira' :{bat:0,ball:0},
            'Sithum' :{bat:0,ball:0},
            'Ranudi' :{bat:0,ball:0},
            'Nethum' :{bat:0,ball:0},
            'Sathsara' :{bat:0,ball:0},
            'Thusith' :{bat:0,ball:0},
            'Banuka' :{bat:0,ball:0},
            'Vishalya' :{bat:0,ball:0}
        }
    },
    
    'Blue Titans': {
        score:0,
        wickets:0, balls:0.0,
        runRate:0,
        extras:0,
        players:{
            'Supun':{bat:0,ball:0},
            'Charindu' :{bat:0,ball:0},
            'Shane' :{bat:0,ball:0},
            'Seth' :{bat:0,ball:0},
            'Dinethma' :{bat:0,ball:0},
            'Janindu' :{bat:0,ball:0},
            'Lahiru' :{bat:0,ball:0},
            'Akindu' :{bat:0,ball:0},
            'Isuru' :{bat:0,ball:0},
            'Manindu' :{bat:0,ball:0},
            'Sakith' :{bat:0,ball:0},
            'Kalpitha' :{bat:0,ball:0},
            'Chamod' :{bat:0,ball:0},
            'Nikila' :{bat:0,ball:0},
            'Lakshitha' :{bat:0,ball:0},
            'Senushka' :{bat:0,ball:0},
            'Hasindu' :{bat:0,ball:0},
            'Vihanga' :{bat:0,ball:0},
            'Pawan':{bat:0,ball:0},
            'Uthsara' :{bat:0,ball:0},
            'Dasun' :{bat:0,ball:0},
            'Himeth' :{bat:0,ball:0},
            'Sanjaya' :{bat:0,ball:0},
            'Nihindu' :{bat:0,ball:0},
            'Chehan' :{bat:0,ball:0},
            'Lakshika' :{bat:0,ball:0},
            'Thushari' :{bat:0,ball:0},
            'Rithara' :{bat:0,ball:0},
            'Jinathi' :{bat:0,ball:0},
            'Oshadhi' :{bat:0,ball:0},
            'Vimalshi' :{bat:0,ball:0},
            'Dilmi' :{bat:0,ball:0},
            'Vihangi' :{bat:0,ball:0},
            'Tharani' :{bat:0,ball:0}
        }
    },

    'Red Raptors':{
        score:0,
        wickets:0, balls:0.0,
        runRate:0,
        extras:0,
        players:{
            'Chamitha':{bat:0,ball:0},
            'Kushad' :{bat:0,ball:0},
            'Nikesh' :{bat:0,ball:0},
            'Chandupa' :{bat:0,ball:0},
            'Samitha' :{bat:0,ball:0},
            'Prashan' :{bat:0,ball:0},
            'Anouk' :{bat:0,ball:0},
            'Anuja' :{bat:0,ball:0},
            'Thilina' :{bat:0,ball:0},
            'Anujaya' :{bat:0,ball:0},
            'Lakmini' :{bat:0,ball:0},
            'Nethmi' :{bat:0,ball:0},
            'Devram' :{bat:0,ball:0},
            'Sanuji' :{bat:0,ball:0},
            'Chamodhi' :{bat:0,ball:0},
            'Jegatheesan' :{bat:0,ball:0},
            'Bineth' :{bat:0,ball:0},
            'Anupa' :{bat:0,ball:0},
            'Movindu' :{bat:0,ball:0},
            'Anuradha' :{bat:0,ball:0},
            'Thanuja' :{bat:0,ball:0},
            'Anusara' :{bat:0,ball:0},
            'Mathisha' :{bat:0,ball:0},
            'Hirushan' :{bat:0,ball:0},
            'Savinu' :{bat:0,ball:0},
            'Navodya' :{bat:0,ball:0},
            'Kithmina' :{bat:0,ball:0},
            'Hansana' :{bat:0,ball:0}

        }
    },

    'Golden Lions':{
        score:0,
        wickets:0, balls:0.0,
        runRate:0,
        extras:0,
        players:{
            'Himeth' :{bat:0,ball:0},
            'Pasindu' :{bat:0,ball:0},
            'Movindu' :{bat:0,ball:0},
            'Muftee' :{bat:0,ball:0},
            'Sahan' :{bat:0,ball:0},
            'Nimeth' :{bat:0,ball:0},
            'Sandaru' :{bat:0,ball:0},
            'Waruna' :{bat:0,ball:0},
            'Anjana' :{bat:0,ball:0},
            'Vishwa' :{bat:0,ball:0},
            'Kavindu' :{bat:0,ball:0},
            'Osanda' :{bat:0,ball:0},
            'Ushan' :{bat:0,ball:0},
            'Raneesha' :{bat:0,ball:0},
            'Thisuru' :{bat:0,ball:0},
            'Shenal' :{bat:0,ball:0},
            'Rahul' :{bat:0,ball:0},
            'Sineth' :{bat:0,ball:0},
            'Jineth' :{bat:0,ball:0},
            'Kevith' :{bat:0,ball:0},
            'Vimukthi' :{bat:0,ball:0},
            'Janindu' :{bat:0,ball:0},
            'Piyath' :{bat:0,ball:0},
            'Thisuri' :{bat:0,ball:0},
            'Nilakna' :{bat:0,ball:0},
            'Venuri' :{bat:0,ball:0},
            'Savithi' :{bat:0,ball:0},
            'Ranugi' :{bat:0,ball:0}

        }
    },

    'Black Panthers':{
        score:0,
        wickets:0, balls:0.0,
        runRate:0,
        extras:0,
        players:{
            'Dinura' :{bat:0,ball:0},
            'Savindu' :{bat:0,ball:0},
            'Nawanka' :{bat:0,ball:0},
            'Harinda' :{bat:0,ball:0},
            'Yasiru' :{bat:0,ball:0},
            'Ravindi' :{bat:0,ball:0},
            'Savinka' :{bat:0,ball:0},
            'Daham' :{bat:0,ball:0},
            'Dhanuja' :{bat:0,ball:0},
            'Himan' :{bat:0,ball:0},
            'Akindu' :{bat:0,ball:0},
            'Sandali' :{bat:0,ball:0},
            'Prabuddhi' :{bat:0,ball:0},
            'Himasara' :{bat:0,ball:0},
            'Pramod' :{bat:0,ball:0},
            'Savin' :{bat:0,ball:0},
            'Tharindu' :{bat:0,ball:0},
            'Sunath' :{bat:0,ball:0},
            'Bishma' :{bat:0,ball:0},
            'Induwara' :{bat:0,ball:0},
            'Dinara' :{bat:0,ball:0},
            'Dasun' :{bat:0,ball:0},
            'Nimeth' :{bat:0,ball:0},
            'Ravindu' :{bat:0,ball:0},
            'Benul' :{bat:0,ball:0},
            'Bashitha' :{bat:0,ball:0},
            'Seniru' :{bat:0,ball:0}

        }
    },

    'Green Gladiators':{
        score:0,
        wickets:0, balls:0.0,
        runRate:0,
        extras:0,
        players:{
            'Kasun' :{bat:0,ball:0},
            'Tharindu' :{bat:0,ball:0},
            'Heshan' :{bat:0,ball:0},
            'Ishan' :{bat:0,ball:0},
            'Shamith' :{bat:0,ball:0},
            'Nethara' :{bat:0,ball:0},
            'Disuru' :{bat:0,ball:0},
            'Ivindu' :{bat:0,ball:0},
            'Tharusha' :{bat:0,ball:0},
            'Vidura' :{bat:0,ball:0},
            'Sandali' :{bat:0,ball:0},
            'Oneli' :{bat:0,ball:0},
            'Nethmi' :{bat:0,ball:0},
            'Binuri' :{bat:0,ball:0},
            'Nadun' :{bat:0,ball:0},
            'Dineth' :{bat:0,ball:0},
            'Sithmi' :{bat:0,ball:0},
            'Rivindu' :{bat:0,ball:0},
            'Rakindu' :{bat:0,ball:0},
            'Pulina' :{bat:0,ball:0}

        }
    }
 } 

